# Generated by Django 3.2.25 on 2024-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstockalert',
            name='alert_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stafflowstockreport',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
