# Generated by Django 3.2.25 on 2024-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CdInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('moviename', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.CharField(max_length=200)),
                ('release_year', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
