# Generated by Django 3.2.25 on 2024-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdinventory',
            name='supplier',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
