# Generated by Django 3.2.25 on 2024-07-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_supplierpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpurchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
